###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mysql:
      image: mysql:5.7
      container_name: desafio-tecnico-mysql
      working_dir: /application
      volumes:
        - .:/application
        - "./transfer:/var/transfer"
        - "./config:/var/config"
        - "./docker/mysql/conf:/etc/mysql/conf.d"
        - "./db:/var/lib/mysql"
      environment:
        - MYSQL_ROOT_PASSWORD=secret
        - MYSQL_DATABASE=desafiotecnico
        - MYSQL_USER=root
        - MYSQL_PASSWORD=secret
      ports:
        - "3380:3306"
      restart: always
    webserver:
      image: nginx:alpine
      container_name: desafio-tecnico-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8180:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: desafio-tecnico-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

    adminer:
      image: adminer
      container_name: desafio-tecnico-adminer
      volumes:
        - ./docker/adminer/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      restart: always
      ports:
        - "8090:8080"







        ###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"

networks:
  desafiotecnico:

services:

  webserver:
    image: nginx:alpine
    container_name: desafiotecnico-webserver
    working_dir: /application
    volumes:
      - .:/application
      - ../packages:/packages
      - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8180:80"
    networks:
      - desafiotecnico

  php-fpm:
    build: phpdocker/php-fpm
    container_name: desafiotecnico-php-fpm
    working_dir: /application
    volumes:
      - .:/application
      - ../packages:/packages
      - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
    networks:
      - desafiotecnico

  mysql:
    image: mysql:8.0
    container_name: desafiotecnico-mysql
    working_dir: /application
    volumes:
      - .:/application
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=desafiotecnico
      - MYSQL_USER=root
      - MYSQL_PASSWORD=secret
    ports:
      - "8182:3306"
    networks:
      - desafiotecnico

  adminer:
    image: adminer
    container_name: desafiotecnico-adminer
    restart: always
    ports:
      - "8190:8080"
    networks:
      - desafiotecnico
