version: "3.1"

networks:
  desafio:

services:

  webserver:
    image: nginx:alpine
    container_name: desafio-webserver
    working_dir: /application
    volumes:
      - .:/application
      - ../packages:/packages
      - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8180:80"
    networks:
      - desafio

  php-fpm:
    build: phpdocker/php-fpm
    container_name: desafio-php-fpm
    working_dir: /application
    volumes:
      - .:/application
      - ../packages:/packages
      - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
    networks:
      - desafio

  mysql:
    image: mysql:8.0
    container_name: desafio-mysql
    working_dir: /application
    volumes:
      - .:/application
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=desafio
      - MYSQL_USER=desafio
      - MYSQL_PASSWORD=secret
    ports:
      - "8086:3306"
    networks:
      - desafio

  adminer:
    image: adminer
    container_name: desafio-adminer
    restart: always
    ports:
      - "8091:8080"
    networks:
      - desafio
